Mobile version
BANCUNGUYE66/Portfolio pull request #1
Opened 2023-02-15 22:54 UTC by BANCUNGUYE66

help me with the review.

2023-02-15 23:34 UTC, Shisui6 reviewed
Hi @BANCUNGUYE66 , 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request 🛠️

You have submitted a project, that;

- Linters are failing. Please go through your code base and check for any errors. Run linter checks on your local machine and fix all warnings that come up
- Does not have a descriptive PR description. Please update your PR description to include a summary of all the changes made in this branch
- Does not contain a readme file. Please make all your future projects use the microverse readme [template](https://github.com/microverseinc/readme-template). When using the microverse template, please fill out and personalize each section to fit your project

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!🍻💻

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid, unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2023-02-16 08:29 UTC, mukhammadrizooff requested changes
Hi @BANCUNGUYE66, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

<img src="https://media3.giphy.com/media/Jq824R93JsLwZCaiSL/giphy.gif"/>

## Highlights
- No linter errors ✔️ 
- Good implementations ✔️ 

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-02-16 08:29 UTC, mukhammadrizooff commented on index.html
> +             <h2>Aima.B</h2>
- [ ] [REQUIRED] Good job so far! The logo should be on the `left`✔️ and has a `link`(a tag)❌ This is for three reasons: `convention`, `semantics`, and `user experience(UX)`. [Check this link](https://ux.stackexchange.com/questions/81727/why-is-it-standard-for-a-website-logo-to-navigate-to-the-home-page) for more info and implement my suggestion please 🙏🏼

2023-02-16 08:29 UTC, mukhammadrizooff commented on index.html
> +               </div>
- [ ] [REQUIRED] Good job so far! Please add correct design to `<a href="#"> LET’S CONNECT</a>` like a [Figma design](https://www.figma.com/file/l7SqJ3ZfkAKih9sFxvWSR4/Microverse-Student-Project-1?node-id=0%3A1&t=w7hRG2wjWSX2EiST-0) 🙏🏼 

![image](https://user-images.githubusercontent.com/63915024/219308501-db157b6e-42c1-4fb7-8dcb-936504fbea27.png)

2023-02-16 08:29 UTC, mukhammadrizooff commented on index.html
> +               </div>
- [ ] [REQUIRED] Good job so far! The `list of icons` should have use a `ul` tag to group them, and `li` per icon; each `icon` should have a `link` (`a` tag).  Apart from being semantically correct, the `a` tag will let you connect your social networks with the icons, using href 🙏🏼

2023-02-16 10:51 UTC, mckent05 approved these changes
Hi @BANCUNGUYE66, 

# STATUS: APPROVED ✔️ ✔️ 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations and well done! 🎉 
![approved](https://user-images.githubusercontent.com/73607512/207264357-1b05ce6a-95f2-4d31-9c26-888c6ddfa124.gif)


## Highlights
- All linter checks are passing ✔️ ✔️ 
- Your PR is professional 👏 👏 

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-02-16 10:51 UTC, mckent05 commented on style.css
> +  }
**OPTIONAL** - Good job using the `background-image` property to display the image for this section, but you have not properly aligned the background image. Please fix this 🙏 

Your project:
-- Please make sure the marked background image is aligned as shown in the Figma design template 🙏 
<img width="449" alt="hw5hw5h" src="https://user-images.githubusercontent.com/73607512/219344469-865c739b-6f16-4334-80ca-f6952d789926.PNG">

Figma template:
<img width="142" alt="header portfolio 2" src="https://user-images.githubusercontent.com/73607512/219344623-2f3cb51c-f99d-4e9b-bd8c-109bd6710008.PNG">

2023-02-16 11:20 UTC, merged