Desktop version
BANCUNGUYE66/Portfolio pull request #5
Opened 2023-02-24 16:58 UTC by BANCUNGUYE66

I added a responsive desktop version for the portfolio. I Used media queries in Css file (min-width: 768px).

2023-02-24 17:36 UTC, Shisui6 requested changes
Hi @BANCUNGUYE66, 

# Requires Changes 🍀
You have done a great job so far!
Your design is good 🖼️, and your code follows best practices. However, there are a few issues that you still need to work on🪲.

## Highlights
- Good design ✅
- Good use of media queries ✅

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you consider them as they can improve your code._

You can also consider the following:

N/A

Cheers and Happy coding!🍻💻

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid, unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561), you have a limited number of reviews per project (check the exact number in your Dashboard). If you think the code review was unfair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-02-24 17:36 UTC, Shisui6 commented on index.html
>     </header>
Kindly update the styling of your headline section to better match the figma design🙏.

Your design:
<img width="541" alt="image" src="https://user-images.githubusercontent.com/37116322/221243236-5332b49b-b457-4df5-a135-feffc20b2449.png">

Figma design:
<img width="482" alt="image" src="https://user-images.githubusercontent.com/37116322/220721486-9c4da92a-169a-4517-a5c6-803b7ae3117a.png">

A few things to note:
- Please use the correct `font-style` `font-size` and `font-weight` for all the text elements. You can click on each element in the figma template and see the styles applied on the inspect panel on the right. I believe the correct font should be `poppins`
- Please put a line break `<br>` between `I'm Aima` and `Glad to see you!`

2023-02-24 17:36 UTC, Shisui6 commented on index.html
> +                     </div>
Kindly update the styling of each of your cards to better match the figma design🙏.

Your design:
<img width="541" alt="image" src="https://user-images.githubusercontent.com/37116322/221244848-36b6657b-8758-491f-966b-9806ffac0d6d.png">

Figma design:
<img width="448" alt="image" src="https://user-images.githubusercontent.com/37116322/221245101-31e15685-d1d2-48f0-978c-5f5dd7d5ab8f.png">

A few things to note:
- Kindly increase the height of each card
- Please increase the left and right margin of each card. Currently your cards are overstretched
- Kindly reduce the left and right padding for each card. 
- Please use the correct `font-style` `font-size` and `font-weight` for each card's text elements. You can click on each element in the figma template and see the styles applied on the inspect panel on the right. I believe the correct font should be `poppins`
- Kindly add button interaction styling to all your cards when the buttons are hovered and pressed. You can do this by using the `:hover` and `:active` pseudo selectors. Please follow the button styling guide provided by figma
<img width="349" alt="image" src="https://user-images.githubusercontent.com/37116322/221246447-2c129242-e4bb-436d-9dd1-31d5ea021f10.png">

2023-02-24 17:36 UTC, Shisui6 commented on index.html
>                 </div>
Kindly update the styling of your about section to better match the figma design🙏.

Your design:
<img width="541" alt="image" src="https://user-images.githubusercontent.com/37116322/221246941-1ba6e13e-aea0-4b49-a0cc-9db08dee3fd8.png">

Figma design:
<img width="482" alt="image" src="https://user-images.githubusercontent.com/37116322/220734894-aebad330-bf70-4957-b6cd-9bd3ac6adf2a.png">

A few things to note:
- Please put a line break `<br>` between `About` and `Myself`
- Please use the correct `font-style` `font-size` and `font-weight` for all the text elements. You can click on each element in the figma template and see the styles applied on the inspect panel on the right. I believe the correct font should be `poppins`
- Kindly increase the top and bottom padding for the technology cards(HTML, CSS, JS) and increase the spacing between the image and the text
- Kindly increase the top and bottom padding for the `frameworks` and `skills` dropdown sections
- Kindly add button interaction styling to the `get my resume` button. Please follow the button styling guide provided by figma
<img width="349" alt="image" src="https://user-images.githubusercontent.com/37116322/221246447-2c129242-e4bb-436d-9dd1-31d5ea021f10.png">

2023-02-24 17:36 UTC, Shisui6 commented on index.html
>                  <ul class="li_st">
Kindly update the styling of your contact section to better match the figma design🙏.

Your design:
<img width="542" alt="image" src="https://user-images.githubusercontent.com/37116322/221248516-dd4b7913-1874-418e-8965-581be402bc0f.png">

Figma design:
<img width="483" alt="image" src="https://user-images.githubusercontent.com/37116322/220737011-e3ada281-0263-4a05-9969-fb30a228d3b7.png">

A few things to note:
- Please increase the width of the main content of the contact section
- Please use the correct `font-style` `font-size` and `font-weight` for all the text elements. You can click on each element in the figma template and see the styles applied on the inspect panel on the right. I believe the correct font should be `poppins`

2023-02-25 01:42 UTC, Favourezeugwa approved these changes
## STATUS: APPROVED 🥇 🏆 🍹 

Hi @BANCUNGUYE66 ,

I am Favour 👩🏽 , your reviewer for this PR.

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Yayyy! 💃🏽, Congratulations! 🎉 🎉🎉

![happy](https://user-images.githubusercontent.com/99246359/202491301-53f8c6a2-8ff4-4337-9b6b-9c75c8bdf345.gif)

## Highlights 💯 
- No Linter errors ✔️
- Good commit messages ✔️
- Professional Readme file ✔️
- Descriptive PR ✔️ 

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-02-25 14:51 UTC, merged